import type { Metadata } from "next";
import "./globals.css";

import { Source_Sans_3 } from "next/font/google";

const source_sans_3 = Source_Sans_3({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${source_sans_3.className} grid justify-items-center min-h-screen antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
